version: '3'
services:
  apache:
    image: httpd:2.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/apache:/usr/local/apache2/conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  pashttpbin1:
    image: pas-httpbin:latest
    volumes:
      - C:/docker/licenses/oe-11.7:/app/license
  pashttpbin2:
    image: pas-httpbin:latest
    volumes:
      - C:/docker/licenses/oe-11.7:/app/license
  pashttpbin3:
    image: pas-httpbin:latest
    volumes:
      - C:/docker/licenses/oe-11.7:/app/license
